name: Deploy a InfinityFree

on:
  push:
    branches:
      - main # Se activarÃ¡ cada vez que hagas push a la rama main

jobs:
  web-deploy:
    name: ðŸŽ‰ Desplegando Proyecto
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Sincronizando CÃ³digo
      uses: actions/checkout@v3

    - name: ðŸ“‚ Subiendo vÃ­a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # /htdocs/ es la carpeta pÃºblica de InfinityFree
        server-dir: /htdocs/ 
        # Excluimos lo que no debe ir al servidor de producciÃ³n
        exclude: |
          **/.git*
          **/.github*
          **/tests*
          .env
          phpunit.xml.dist
          docker-compose.yml
          Dockerfile
          README.md